"""Khởi tạo lược đồ 10 bảng (plan.md §5.9).

Revision ID: 0001
Revises:
Create Date: 2026-10-06 10:13:17.896314+07:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_table(
        "job_runs",
        sa.Column("job_name", sa.String(length=64), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
    )
    op.create_index(op.f("ix_job_runs_job_name"), "job_runs", ["job_name"], unique=False)
    op.create_table(
        "llm_credentials",
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("secret_enc", sa.String(), nullable=False),
        sa.Column("hint", sa.String(length=16), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('google_api_key', 'fb_cookie')", name=op.f("ck_llm_credentials_kind_known")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_credentials")),
        sa.UniqueConstraint("kind", name=op.f("uq_llm_credentials_kind")),
    )
    op.create_table(
        "llm_settings",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("max_output_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "provider = '' OR provider IN ('antigravity', 'google_api_key')",
            name=op.f("ck_llm_settings_provider_known"),
        ),
        sa.CheckConstraint(
            "temperature >= 0 AND temperature <= 2", name=op.f("ck_llm_settings_temperature_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_settings")),
    )
    op.create_table(
        "profiles",
        sa.Column("facebook_url", sa.Text(), nullable=False),
        sa.Column("url_key", sa.String(length=255), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=True),
        sa.Column("visual_context", sa.Text(), nullable=True),
        sa.Column("demographics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profiles")),
        sa.UniqueConstraint("url_key", name=op.f("uq_profiles_url_key")),
    )
    op.create_index(
        "ix_profiles_created_at_desc", "profiles", [sa.text("created_at DESC")], unique=False
    )
    op.create_index(op.f("ix_profiles_status"), "profiles", ["status"], unique=False)
    op.create_table(
        "evening_hooks",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("based_on", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_evening_hooks_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evening_hooks")),
    )
    op.create_index(
        op.f("ix_evening_hooks_generated_at"), "evening_hooks", ["generated_at"], unique=False
    )
    op.create_table(
        "profile_evidence",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("bundle", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("collector_layers", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("screenshot_path", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_profile_evidence_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_evidence")),
    )
    op.create_table(
        "rapport_runs",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("empathy_angle", sa.Text(), nullable=True),
        sa.Column("sales_check", sa.String(length=32), nullable=False),
        sa.Column("grounding_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("token_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sales_check IN ('ZERO_SALES_CONFIRMED', 'FAILED')",
            name=op.f("ck_rapport_runs_sales_check_known"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_rapport_runs_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rapport_runs")),
    )
    op.create_table(
        "outbox",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("hook_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'approved', 'sent_manually', 'discarded')",
            name=op.f("ck_outbox_status_known"),
        ),
        sa.ForeignKeyConstraint(
            ["hook_id"],
            ["evening_hooks.id"],
            name=op.f("fk_outbox_hook_id_evening_hooks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_outbox_profile_id_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
    )
    op.create_index(
        "ix_outbox_status_scheduled_for", "outbox", ["status", "scheduled_for"], unique=False
    )
    op.create_table(
        "rapport_messages",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["rapport_runs.id"],
            name=op.f("fk_rapport_messages_run_id_rapport_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rapport_messages")),
        sa.UniqueConstraint("run_id", "seq", name="run_seq_unique"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rapport_messages")
    op.drop_index("ix_outbox_status_scheduled_for", table_name="outbox")
    op.drop_table("outbox")
    op.drop_table("rapport_runs")
    op.drop_table("profile_evidence")
    op.drop_index(op.f("ix_evening_hooks_generated_at"), table_name="evening_hooks")
    op.drop_table("evening_hooks")
    op.drop_index(op.f("ix_profiles_status"), table_name="profiles")
    op.drop_index("ix_profiles_created_at_desc", table_name="profiles")
    op.drop_table("profiles")
    op.drop_table("llm_settings")
    op.drop_table("llm_credentials")
    op.drop_index(op.f("ix_job_runs_job_name"), table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
