"""Phien hoi thoai nhieu luot (task.md X.3).

Ba bang: `conversations`, `conversation_messages` (nhung gi DA xay ra that),
`conversation_suggestions` (nhung gi AI DE XUAT). Tach hai bang sau la co chu
dich — tron chung thi khong con phan biet duoc "da gui" voi "moi chi goi y",
ma do dung la ranh gioi luat L3 bao ve.

LUU Y (task.md I-48): autogenerate muon DROP `apscheduler_jobs`. Bang do do
APScheduler tu tao va tu quan ly, khong nam trong metadata cua app — de nguyen
lenh drop thi `alembic upgrade head` se XOA LICH 20h. Da go bo thu cong o ca
upgrade lan downgrade.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-07
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'closed')", name=op.f('ck_conversations_status_known')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_conversations_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_profile_created', 'conversations', ['profile_id', 'created_at'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('operator', 'customer')", name=op.f('ck_conversation_messages_role_known')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages'))
    )
    op.create_index('ix_conversation_messages_seq', 'conversation_messages', ['conversation_id', 'seq'], unique=True)
    op.create_table('conversation_suggestions',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chosen', sa.Boolean(), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_suggestions_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_suggestions'))
    )
    op.create_index('ix_conversation_suggestions_round', 'conversation_suggestions', ['conversation_id', 'round', 'seq'], unique=True)
    # KHONG drop `apscheduler_jobs` — xem docstring dau file (I-48).


def downgrade() -> None:
    # Khong dung toi `apscheduler_jobs` — no khong thuoc migration nay (I-48).
    op.drop_index('ix_conversation_suggestions_round', table_name='conversation_suggestions')
    op.drop_table('conversation_suggestions')
    op.drop_index('ix_conversation_messages_seq', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('ix_conversations_profile_created', table_name='conversations')
    op.drop_table('conversations')
